language: node_js
node_js:
  - "8"
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'create database "orm-query-builder";' -U postgres
  - npm run migrate
after_success:
  - npm run test:coveralls
